import characteristic_p_methods_frobenius_endomorphism_foundation_canonical_lane_mathlib.GateLemmas
import characteristic_p_methods_frobenius_endomorphism_foundation_canonical_lane_mathlib.FinalTheorem
